/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#9df4c8",
        "on-background": "#1a1b20",
        "tertiary-container": "#131b2e",
        "success-green": "#006c49",
        background: "#f9f9ff",
        "surface-container": "#ededf4",
        "outline-variant": "#c6c6cd",
        "primary-container": "#1b1b1b",
        "on-tertiary-fixed-variant": "#3f465b",
        "secondary-fixed-dim": "#81d8ad",
        primary: "#000000",
        "on-primary": "#ffffff",
        "deep-navy": "#131b2e",
        "inverse-surface": "#2f3035",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#002113",
        "on-primary-fixed": "#1b1b1b",
        "secondary-container": "#9af2c5",
        "surface-container-highest": "#e2e2e9",
        "on-tertiary-container": "#7c839b",
        "on-primary-fixed-variant": "#474747",
        "on-error-container": "#93000a",
        "surface-tint": "#5e5e5e",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3fa",
        "on-surface-variant": "#4c4546",
        outline: "#7e7576",
        "on-secondary-fixed-variant": "#005236",
        "surface-variant": "#e2e2e9",
        "primary-fixed-dim": "#c6c6c6",
        "on-surface": "#1a1b20",
        "on-primary-container": "#848484",
        "tertiary-fixed": "#dae2fc",
        error: "#ba1a1a",
        "surface-dim": "#d9d9e0",
        surface: "#f9f9ff",
        tertiary: "#000000",
        "on-secondary-container": "#0c714d",
        "primary-fixed": "#e2e2e2",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e8e7ee",
        "tertiary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#f0f0f7",
        "inverse-primary": "#c6c6c6",
        "on-tertiary-fixed": "#131b2e",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9ff",
        secondary: "#006c49",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-margin": "1rem",
        "stack-gap": "1.5rem",
        "inline-gap": "0.75rem",
        "card-padding": "1.25rem",
        "section-margin": "2rem",
      },
      fontFamily: {
        "data-mono": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "label-xs": ["Inter", "sans-serif"],
        "label-bold": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": [
          "30px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-xs": ["10px", { lineHeight: "12px", fontWeight: "600" }],
        "label-bold": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
